#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npm test

branch="$(git rev-parse --abbrev-ref HEAD)"
RED='\033[0;31m'
NC='\033[0m' # No Color

if [ "$branch" = "main" ]; then
  echo "${RED}[ERROR]${NC}: You can't commit directly to ${RED}main${NC} branch"
  exit 1
fi
