name: Report Coverage
on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - main

jobs:
  coverage:
    uses: "Coaktion/aktie-devops/.github/workflows/coverage.yml@main"
    with:
      node_version: 18.x
