name: Node.js Package

on:
  release:
    types: [published]

jobs:
  publish:
    uses: "Coaktion/aktie-devops/.github/workflows/npm-publish.yml@main"
    with:
      open_source: true
    secrets: inherit
